# Generated by Django 4.0.4 on 2022-07-24 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=13, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='v1.card')),
                ('to_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.card')),
            ],
        ),
    ]
